# Generated by Django 3.2.5 on 2021-07-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_user_add_subscription_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponybotuser',
            options={'verbose_name': 'Ponybot User', 'verbose_name_plural': 'Ponybot Users'},
        ),
    ]
