# Generated by Django 3.2.5 on 2021-07-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_add_ponybot_action_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='User Id')),
                ('peer_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Peer Id')),
                ('action_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Action Id')),
                ('opened', models.BooleanField(default=True, verbose_name='Opened')),
            ],
            options={
                'verbose_name': 'Dialog Session',
                'verbose_name_plural': 'Dialog Sessions',
            },
        ),
    ]
