# Generated by Django 3.2.5 on 2021-07-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_add_session_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogsession',
            name='last_message',
            field=models.JSONField(default=dict, verbose_name='Last Message'),
        ),
    ]
