# Generated by Django 3.2.5 on 2021-07-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0006_alter_pony_add_last_feeding_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='first_feeding',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
