# Generated by Django 3.2.5 on 2021-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0007_alter_pony_add_first_feeding_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='Is pony alive'),
        ),
    ]
