# Generated by Django 3.2.5 on 2021-07-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0009_alter_pony_add_field_last_learning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pony',
            name='first_feeding',
        ),
    ]
