# Generated by Django 3.2.5 on 2021-07-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0010_alter_pony_drop_first_feeding_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='conversation',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Conversation peer id'),
        ),
        migrations.AddField(
            model_name='pony',
            name='owner',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Owner user id'),
        ),
    ]
