# Generated by Django 3.2.5 on 2021-07-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0012_adding_sex_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pony',
            options={'ordering': ('owner', 'name', 'last_feeding', 'last_learning'), 'verbose_name': 'Pony', 'verbose_name_plural': 'Ponies'},
        ),
        migrations.AddField(
            model_name='pony',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Pony avatar url'),
        ),
    ]
