# Generated by Django 3.2.5 on 2021-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0014_renaming_sex_field_to_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pony',
            name='conversation',
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name='Conversation'),
        ),
    ]
