# Generated by Django 3.2.5 on 2021-07-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0016_alter_pony_add_conversation_title_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='owner_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Owner title'),
        ),
    ]
