# Generated by Django 3.2.5 on 2021-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0017_alter_pony_add_owner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pony',
            name='last_feeding',
            field=models.DateTimeField(null=True, verbose_name='Last feeding'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='last_learning',
            field=models.DateTimeField(null=True, verbose_name='Last learning'),
        ),
    ]
