# Generated by Django 3.2.5 on 2021-07-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Action Name')),
                ('aliases', models.JSONField(default=list, verbose_name='Action aliases')),
                ('is_admin_only', models.BooleanField(default=False, verbose_name='Is admin only')),
            ],
            options={
                'verbose_name': 'Ponybot Action',
                'verbose_name_plural': 'Ponybot Actions',
            },
        ),
        migrations.CreateModel(
            name='DialogSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='User Id')),
                ('peer_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='Peer Id')),
                ('action_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Action Id')),
                ('last_message', models.JSONField(default=dict, verbose_name='Last Message')),
                ('opened', models.BooleanField(default=True, verbose_name='Opened')),
            ],
            options={
                'verbose_name': 'Dialog Session',
                'verbose_name_plural': 'Dialog Sessions',
            },
        ),
    ]
