# Generated by Django 3.2.5 on 2021-07-05 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pony',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4, editable=False,
                 primary_key=True, serialize=False, verbose_name='ID'
                 )),
            ],
        ),
    ]
