# Generated by Django 3.2.5 on 2021-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0001_create_pony_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Pony name'),
        ),
    ]
