# Generated by Django 3.2.5 on 2021-07-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0003_alter_pony_add_field_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='satiety',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Pony satiety'),
        ),
    ]
