# Generated by Django 3.2.5 on 2021-07-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0005_alter_pony_add_pk_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='last_feeding',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
