# Generated by Django 3.2.5 on 2021-07-06 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pony', '0009_alter_pony_add_last_learning_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pony',
            options={'verbose_name': 'Pony', 'verbose_name_plural': 'Ponies'},
        ),
        migrations.AddField(
            model_name='pony',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
