# Generated by Django 3.2.5 on 2021-07-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0010_alter_pony_add_owner_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pony',
            name='first_feeding',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
