# Generated by Django 3.2.5 on 2021-07-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0011_alter_pony_auto_add_first_feeding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pony',
            options={'ordering': ('name', 'owner', 'last_feeding', 'last_learning'), 'verbose_name': 'Pony', 'verbose_name_plural': 'Ponies'},
        ),
    ]
