# Generated by Django 3.2.5 on 2021-07-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0012_alter_pony_add_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pony',
            options={'ordering': ('owner', 'name', 'last_feeding', 'last_learning'), 'verbose_name': 'Pony', 'verbose_name_plural': 'Ponies'},
        ),
        migrations.RemoveField(
            model_name='pony',
            name='first_feeding',
        ),
        migrations.AlterField(
            model_name='pony',
            name='last_learning',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
