# Generated by Django 3.2.5 on 2021-07-13 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0013_adding_avatar_url_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pony',
            name='sex',
        ),
        migrations.AddField(
            model_name='pony',
            name='race',
            field=models.CharField(choices=[('Земнопони', 'Earthpony'), ('Пегас', 'Pegasus'), ('Единорог', 'Unicorn'), ('Аликорн', 'Alicorn')], default='Земнопони', max_length=12, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='conversation',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='experience',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='Is alive'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='last_feeding',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last feeding'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='last_learning',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last learning'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='owner',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='satiety',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='Satiety'),
        ),
    ]
