# Generated by Django 3.2.5 on 2021-07-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0013_alter_pony_alter_timestamps_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='sex',
            field=models.CharField(choices=[('EARTHPONY', 'Earthpony'), ('PEGASUS', 'Pegasus'), ('UNICORN', 'Unicorn'), ('ALICORN', 'Alicorn')], default='EARTHPONY', max_length=12, verbose_name='Pony sex'),
        ),
    ]
