# Generated by Django 3.2.5 on 2021-07-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0014_alter_pony_add_field_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pony',
            name='owner',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Owner user id'),
        ),
    ]
