# Generated by Django 3.2.5 on 2021-07-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0015_alter_pony_update_field_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='conversation',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Conversation peer id'),
        ),
        migrations.AlterField(
            model_name='pony',
            name='sex',
            field=models.CharField(choices=[('Земнопони', 'Earthpony'), ('Пегас', 'Pegasus'), ('Единорог', 'Unicorn'), ('Аликорн', 'Alicorn')], default='Земнопони', max_length=12, verbose_name='Pony sex'),
        ),
    ]
