# Generated by Django 3.2.5 on 2021-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pony', '0015_alter_pony_rollback_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pony',
            name='conversation_title',
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name='Conversation title'),
        ),
    ]
